# Generated by Django 5.2.3 on 2025-06-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_customuser_avatar_customuser_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=11, verbose_name="Номер телефона"
            ),
        ),
    ]
