# Generated by Django 5.2.3 on 2025-06-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                max_length=11, null=True, unique=True, verbose_name="Номер телефона"
            ),
        ),
    ]
