# Generated by Django 5.2.3 on 2025-06-10 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("body", models.TextField(verbose_name="Body")),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("full_name", models.CharField(verbose_name="Full Name")),
                ("comment", models.TextField(verbose_name="Comment")),
            ],
            options={
                "verbose_name": "Recipient",
                "verbose_name_plural": "Recipients",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="MailingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_first_sent",
                    models.DateField(auto_now_add=True, verbose_name="Date First Sent"),
                ),
                (
                    "date_last_sent",
                    models.DateField(auto_now=True, verbose_name="Date Last Sent"),
                ),
                ("status", models.CharField(verbose_name="Status")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sender.message",
                        verbose_name="Message",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        to="sender.recipient", verbose_name="Recipients"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SendAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Date")),
                ("status", models.CharField(max_length=50, verbose_name="Status")),
                ("response", models.TextField(verbose_name="Response")),
                (
                    "mailing_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sender.mailinglist",
                        verbose_name="Mailing List",
                    ),
                ),
            ],
        ),
    ]
