# Generated by Django 5.2.3 on 2025-06-12 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["title"],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["email"],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="sendattempt",
            options={
                "ordering": ["status", "date"],
                "verbose_name": "Состояние рассылки",
                "verbose_name_plural": "Состояния рассылок",
            },
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="date_first_sent",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата первой отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="date_last_sent",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последней отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sender.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="recipients",
            field=models.ManyToManyField(
                to="sender.recipient", verbose_name="Получатели"
            ),
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Запущена"),
                    ("completed", "Завершена"),
                ],
                default="created",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(verbose_name="Тело письма"),
        ),
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Тема письма"),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="comment",
            field=models.TextField(verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="full_name",
            field=models.CharField(verbose_name="Ф. И. О."),
        ),
        migrations.AlterField(
            model_name="sendattempt",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="sendattempt",
            name="mailing_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sender.mailinglist",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="sendattempt",
            name="response",
            field=models.TextField(verbose_name="Ответ сервера"),
        ),
        migrations.AlterField(
            model_name="sendattempt",
            name="status",
            field=models.CharField(max_length=50, verbose_name="Статус"),
        ),
    ]
