# Generated by Django 5.2.3 on 2025-06-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0007_message_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sendattempt",
            options={
                "ordering": ["status", "date"],
                "permissions": [("can_view_attempts", "Can view sent attempts")],
                "verbose_name": "Состояние рассылки",
                "verbose_name_plural": "Состояния рассылок",
            },
        ),
        migrations.RenameField(
            model_name="mailinglist",
            old_name="user",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="user",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="recipient",
            old_name="user",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="sendattempt",
            old_name="user",
            new_name="owner",
        ),
    ]
